package timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author toringje_sd2082
 */
public class Digital extends javax.swing.JFrame {

    /**
     * Creates new form Digital
     */
    String str;
    private boolean states;
    static Thread thread;
    static Date dd;
    static Timer timer;
    int count = 11;

    public Digital() {
        initComponents();
        stop.setEnabled(false);
        reset.setEnabled(false);
        watch t = new watch();
        t.start();
        str = "";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        colon1 = new javax.swing.JLabel();
        hours = new javax.swing.JLabel();
        seconds = new javax.swing.JLabel();
        colon2 = new javax.swing.JLabel();
        minutes = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        stoptext = new javax.swing.JLabel();
        colon3 = new javax.swing.JLabel();
        milliseconds = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        currenttext = new javax.swing.JLabel();
        Time = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        downtext = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        countdown2 = new javax.swing.JButton();
        start1button = new javax.swing.JButton();
        stop1button = new javax.swing.JButton();
        panel5 = new javax.swing.JPanel();
        uptext = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COUNTDOWN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(0, 0, 0));

        colon1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        colon1.setForeground(new java.awt.Color(255, 255, 255));
        colon1.setText(":");
        colon1.setMaximumSize(new java.awt.Dimension(24, 20));

        hours.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        hours.setForeground(new java.awt.Color(255, 255, 255));
        hours.setText(" 00");
        hours.setMaximumSize(new java.awt.Dimension(24, 20));

        seconds.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        seconds.setForeground(new java.awt.Color(255, 255, 255));
        seconds.setText("00");
        seconds.setMaximumSize(new java.awt.Dimension(24, 20));

        colon2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        colon2.setForeground(new java.awt.Color(255, 255, 255));
        colon2.setText(":");
        colon2.setMaximumSize(new java.awt.Dimension(24, 20));

        minutes.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        minutes.setForeground(new java.awt.Color(255, 255, 255));
        minutes.setText(" 00");
        minutes.setMaximumSize(new java.awt.Dimension(24, 20));

        start.setText("START");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        stop.setText("STOP");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        stoptext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stoptext.setForeground(new java.awt.Color(255, 0, 153));
        stoptext.setText("STOPWATCH");

        colon3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        colon3.setForeground(new java.awt.Color(255, 255, 255));
        colon3.setText(":");
        colon3.setMaximumSize(new java.awt.Dimension(24, 20));

        milliseconds.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        milliseconds.setForeground(new java.awt.Color(255, 255, 255));
        milliseconds.setText("00");
        milliseconds.setMaximumSize(new java.awt.Dimension(24, 20));

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(stoptext))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(colon1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(start, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colon2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seconds, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colon3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(milliseconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stoptext)
                .addGap(47, 47, 47)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colon1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colon2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(milliseconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colon3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        panel2.setBackground(new java.awt.Color(153, 153, 153));

        currenttext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        currenttext.setForeground(new java.awt.Color(0, 255, 51));
        currenttext.setText("CURRENT TIME");

        Time.setBackground(new java.awt.Color(255, 153, 153));
        Time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currenttext)
                .addGap(109, 109, 109))
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currenttext)
                .addGap(83, 83, 83)
                .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel3.setBackground(new java.awt.Color(255, 51, 153));

        downtext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        downtext.setForeground(new java.awt.Color(255, 255, 255));
        downtext.setText("COUNTDOWN");

        countdown2.setBackground(new java.awt.Color(0, 0, 0));
        countdown2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        countdown2.setForeground(new java.awt.Color(255, 255, 255));
        countdown2.setText("00");
        countdown2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        countdown2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countdown2ActionPerformed(evt);
            }
        });

        start1button.setText("START");
        start1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start1buttonActionPerformed(evt);
            }
        });

        stop1button.setText("STOP");
        stop1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop1buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(countdown2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel3Layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(downtext))
                        .addGroup(panel3Layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(start1button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(stop1button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(downtext)
                .addGap(38, 38, 38)
                .addComponent(countdown2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start1button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stop1button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel5.setBackground(new java.awt.Color(51, 153, 255));

        uptext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uptext.setForeground(new java.awt.Color(255, 255, 255));
        uptext.setText("COUNT UP");

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(uptext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uptext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        start.setEnabled(false);
        stop.setEnabled(true);
        reset.setEnabled(true);
        str = "Start";

    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        str = "Stop";
        start.setEnabled(true);
        stop.setEnabled(false);
        reset.setEnabled(true);
    }//GEN-LAST:event_stopActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        str = "Reset";
        start.setEnabled(true);
        stop.setEnabled(true);
        reset.setEnabled(false);


    }//GEN-LAST:event_resetActionPerformed

    private void TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeActionPerformed
        // TODO add your handling code here:
        states = true;
        Thread t = new Thread() {

            public void run() {
                for (;;) {
                    if (states == true) {
                        try {
                            do {
                                dd = new Date();
                                SimpleDateFormat simple = new SimpleDateFormat("hh:mm:ss a");
                                Time.setText(simple.format(dd));
                                Thread.sleep(1000);  // 1000 = 1 second
                            } while (thread.isAlive());
                        } catch (Exception e) {

                        }

                    } else {
                        break;
                    }
                }
            }

        };
        t.start();


    }//GEN-LAST:event_TimeActionPerformed

    private void countdown2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countdown2ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_countdown2ActionPerformed

    private void start1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start1buttonActionPerformed
        // TODO add your handling code here:

        timer = new Timer(1000, new ActionListener() {
            

            @Override
            public void actionPerformed(ActionEvent e) {
                count--;
                countdown2.setText("" + count);

            }
        });
        timer.start();

    
    }//GEN-LAST:event_start1buttonActionPerformed

    private void stop1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop1buttonActionPerformed
        // TODO add your handling code here:
        timer.stop();
    }//GEN-LAST:event_stop1buttonActionPerformed

    private void digitalclockActionPerformed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                



}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Digital.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 



catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Digital.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 



catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Digital.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 



catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Digital.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Digital().setVisible(true);
            }
        });
    



}

    class watch extends Thread {

    int h = 0, m = 0, s = 0, ms = 0;

    public void run() {
        for (;;) {
            try {
                sleep(1);
                if (str.equals("Start")) {
                    ms++;
                    if (ms >= 1000 && s != 60 && m != 60) {
                        s++;
                        ms = 0;
                    }

                    if (ms >= 1000 && s >= 60 && m != 60) {

                        m++;
                        s = 0;
                        ms = 0;
                    }
                    if (ms >= 1000 && s >= 60 && m >= 60) {
                        h++;
                        m = 0;
                        s = 0;
                        ms = 0;
                    }
                    hours.setText(Integer.toString(h));
                    minutes.setText(Integer.toString(m));
                    seconds.setText(Integer.toString(s));
                    milliseconds.setText(Integer.toString(ms));
                }
                if (str.equals("Reset")) {
                    h = 0;
                    m = 0;
                    s = 0;
                    ms = 0;
                    hours.setText(Integer.toString(h));
                    minutes.setText(Integer.toString(m));
                    seconds.setText(Integer.toString(s));
                    milliseconds.setText(Integer.toString(ms));
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton Time;
    private javax.swing.JLabel colon1;
    private javax.swing.JLabel colon2;
    private javax.swing.JLabel colon3;
    private javax.swing.JButton countdown2;
    private javax.swing.JLabel currenttext;
    private javax.swing.JLabel downtext;
    private javax.swing.JLabel hours;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel milliseconds;
    private javax.swing.JLabel minutes;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel5;
    private javax.swing.JButton reset;
    private javax.swing.JLabel seconds;
    private javax.swing.JButton start;
    private javax.swing.JButton start1button;
    private javax.swing.JButton stop;
    private javax.swing.JButton stop1button;
    private javax.swing.JLabel stoptext;
    private javax.swing.JLabel uptext;
    // End of variables declaration//GEN-END:variables
}
